### PR TITLE
lib: Fix abort on monitored net address removal.

### LINKED ISSUE #27: mptcpd aborts when removing an address from monitoring
**Describe the bug**
An `assert()` in the `mptcpd` network monitor is triggered when it handles an rtnetlink [`RTM_DELADDR`](https://linux.die.net/man/7/rtnetlink) message.  There are two problems with the code:

* The `assert()` that checks the "right hand side" argument's address family in this case is unnecessary.
* The `user_data` argument to the `mptcpd_in_addr_match()` is incorrectly assumed to be of type `struct mptcpd_in_addr` when it is actually `void*` that contains either a `in_addr_t*` or `in6_addr_t*`, depending on the address family found in the `RTM_DELADDR` message.

**Expected behavior**
No abort, and no crash due to function parameter mismatch.

**Screenshots**
From the host's systemd journal:
```
Jun 04 13:37:04 mptcp-vm-server mptcpd[6299]: mptcpd: network_monitor.c:152: mptcpd_in_addr_match: Assertion `rhs->family == AF_INET || rhs->family == AF_INET6' failed.
```

**Desktop (please complete the following information):**
 - Linux Kernel: 4.19 (multipath-tcp.org 0.95 kernel)
 - Compiler: gcc 8.30

### PR DESCRIPTION
**Pull request by ossama-othman**
The network monitor code that removes a network address from
monitoring had a function parameter mismatch that was hidden a pointer
to void.  Correct the mismatch, and make all network monitor functions
that support the RTM_NEWADDR, RTM_DELADDR, and RTM_GETADDR rtnetlink
messages consistently use the same (internal) network address
information encapsulation type.  Fixes #27.

### CODE REVIEW

File: lib/network_monitor.c [hunk 1]
```diff
@@ -132,42 +159,56 @@ mptcpd_in_addr_compare(void const *a, void const *b, void *user_data)
...
-                        matched = (lhs->addr.addr4.s_addr
-                                   == rhs->addr.addr4.s_addr);
-                else
+                if (lhs->family == AF_INET) {
+                        /*
+                          Kernel nla_put_in_addr() inserts a big
+                          endian 32 bit unsigned integer, not struct
+                          in_addr.
+                        */
+                        in_addr_t const sa = *(uint32_t const*) rhs->addr;
```
Comment (mjmartineau) [inline lib/network_monitor.c]: Same question as line 108 about `in_addr_t` and `uint32_t`

File: lib/network_monitor.c [hunk 2]
```diff
@@ -53,37 +53,64 @@ struct mptcpd_nm
...
 
-        if (ifa->ifa_family == AF_INET) {
+        if (family == AF_INET) {
                 /*
                   Kernel nla_put_in_addr() inserts a big endian 32
                   bit unsigned integer, not struct in_addr.
                 */
                 in_addr_t const sa =
-                        *(uint32_t const*) data;
+                        *(uint32_t const*) info->addr;
```
Comment (mjmartineau) [inline lib/network_monitor.c]: Do you need the intermediate `sa` variable here?

The `in_addr_t` vs `uint32_t` mismatch on each side of the assignment catches my eye. I realize they're equivalent, does it help anything to use them this way?

Comment (ossama-othman) [reply lib/network_monitor.c]: Not at all.  I'll drop the in_addr_t in this case, and the other one you mentioned.
