### PR TITLE
network_monitor: Fix netlink related memory leak.

### LINKED ISSUE #17: test-path-manager leaks memory
**Describe the bug**
The unit test `tests/test-path-manager` leaks memory, and contains memory violations despite a successful run.

**To Reproduce**
1. `./configure --enable-debug`
2. `make check`
3. `./libtool --mode=execute valgrind --leak-check=full tests/test-path-manager`

**Expected behavior**
No leaks should be detected at `test-path-manager` process exit.  The Valgrind summary should look similar to the following, in particular "`no leaks possible`":
```
==26069== HEAP SUMMARY:
==26069==     in use at exit: 0 bytes in 0 blocks
==26069==   total heap usage: 37 allocs, 37 frees, 30,696 bytes allocated
==26069== 
==26069== All heap blocks were freed -- no leaks are possible
==26069== 
==26069== For counts of detected and suppressed errors, rerun with: -v
==26069== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
**Screenshots**
```
==25640== Memcheck, a memory error detector
==25640== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==25640== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==25640== Command: /home/void/MPTCP/OTC/mptcpd/genl-update/tests/.libs/test-path-manager
==25640== 
configuration.c:check_file_perms() File "/usr/local/etc/mptcpd/mptcpd.conf" does not exist.
configuration.c:parse_config_file() Unable to mptcpd load settings from file '/usr/local/etc/mptcpd/mptcpd.conf'
configuration.c:mptcpd_config_create() plugin directory: /home/void/MPTCP/OTC/mptcpd/genl-update/tests/plugins_noop
TEST: pm_create
TEST: pm_destroy
==25640== Invalid read of size 8
==25640==    at 0x485D11B: l_queue_push_tail (queue.c:141)
==25640==    by 0x4863F15: l_netlink_send (netlink.c:438)
==25640==    by 0x484939B: send_getaddr_command (network_monitor.c:845)
==25640==    by 0x4863792: destroy_command (netlink.c:76)
==25640==    by 0x485D9DB: l_hashmap_destroy (hashmap.c:336)
==25640==    by 0x4863DC9: l_netlink_destroy (netlink.c:379)
==25640==    by 0x4849F0B: mptcpd_nm_destroy (network_monitor.c:972)
==25640==    by 0x10BD17: mptcpd_pm_destroy (path_manager.c:764)
==25640==    by 0x10A4AE: test_pm_destroy (test-path-manager.c:51)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==  Address 0x4ac6948 is 8 bytes inside a block of size 24 free'd
==25640==    at 0x483997B: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25640==    by 0x4863DAE: l_netlink_destroy (netlink.c:377)
==25640==    by 0x4849F0B: mptcpd_nm_destroy (network_monitor.c:972)
==25640==    by 0x10BD17: mptcpd_pm_destroy (path_manager.c:764)
==25640==    by 0x10A4AE: test_pm_destroy (test-path-manager.c:51)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==    by 0x485D4D7: l_queue_foreach (queue.c:441)
==25640==    by 0x4860B0C: l_main_iterate (main.c:486)
==25640==    by 0x4860B8B: l_main_run (main.c:520)
==25640==    by 0x10A5C6: main (test-path-manager.c:127)
==25640==  Block was alloc'd at
==25640==    at 0x483874F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25640==    by 0x485B76D: l_malloc (util.c:62)
==25640==    by 0x485D04D: l_queue_new (queue.c:63)
==25640==    by 0x4863D1D: l_netlink_new (netlink.c:359)
==25640==    by 0x484A008: mptcpd_nm_create (network_monitor.c:873)
==25640==    by 0x10BE04: mptcpd_pm_create (path_manager.c:748)
==25640==    by 0x10A3E0: test_pm_create (test-path-manager.c:38)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==    by 0x485D4D7: l_queue_foreach (queue.c:441)
==25640==    by 0x4860B0C: l_main_iterate (main.c:486)
==25640== 
==25640== Invalid read of size 8
==25640==    at 0x485D133: l_queue_push_tail (queue.c:146)
==25640==    by 0x4863F15: l_netlink_send (netlink.c:438)
==25640==    by 0x484939B: send_getaddr_command (network_monitor.c:845)
==25640==    by 0x4863792: destroy_command (netlink.c:76)
==25640==    by 0x485D9DB: l_hashmap_destroy (hashmap.c:336)
==25640==    by 0x4863DC9: l_netlink_destroy (netlink.c:379)
==25640==    by 0x4849F0B: mptcpd_nm_destroy (network_monitor.c:972)
==25640==    by 0x10BD17: mptcpd_pm_destroy (path_manager.c:764)
==25640==    by 0x10A4AE: test_pm_destroy (test-path-manager.c:51)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==  Address 0x4ac6940 is 0 bytes inside a block of size 24 free'd
==25640==    at 0x483997B: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25640==    by 0x4863DAE: l_netlink_destroy (netlink.c:377)
==25640==    by 0x4849F0B: mptcpd_nm_destroy (network_monitor.c:972)
==25640==    by 0x10BD17: mptcpd_pm_destroy (path_manager.c:764)
==25640==    by 0x10A4AE: test_pm_destroy (test-path-manager.c:51)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==    by 0x485D4D7: l_queue_foreach (queue.c:441)
==25640==    by 0x4860B0C: l_main_iterate (main.c:486)
==25640==    by 0x4860B8B: l_main_run (main.c:520)
==25640==    by 0x10A5C6: main (test-path-manager.c:127)
==25640==  Block was alloc'd at
==25640==    at 0x483874F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25640==    by 0x485B76D: l_malloc (util.c:62)
==25640==    by 0x485D04D: l_queue_new (queue.c:63)
==25640==    by 0x4863D1D: l_netlink_new (netlink.c:359)
==25640==    by 0x484A008: mptcpd_nm_create (network_monitor.c:873)
==25640==    by 0x10BE04: mptcpd_pm_create (path_manager.c:748)
==25640==    by 0x10A3E0: test_pm_create (test-path-manager.c:38)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==    by 0x485D4D7: l_queue_foreach (queue.c:441)
==25640==    by 0x4860B0C: l_main_iterate (main.c:486)
==25640== 
==25640== Invalid write of size 8
==25640==    at 0x485D137: l_queue_push_tail (queue.c:144)
==25640==    by 0x4863F15: l_netlink_send (netlink.c:438)
==25640==    by 0x484939B: send_getaddr_command (network_monitor.c:845)
==25640==    by 0x4863792: destroy_command (netlink.c:76)
==25640==    by 0x485D9DB: l_hashmap_destroy (hashmap.c:336)
==25640==    by 0x4863DC9: l_netlink_destroy (netlink.c:379)
==25640==    by 0x4849F0B: mptcpd_nm_destroy (network_monitor.c:972)
==25640==    by 0x10BD17: mptcpd_pm_destroy (path_manager.c:764)
==25640==    by 0x10A4AE: test_pm_destroy (test-path-manager.c:51)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==  Address 0x4ac6948 is 8 bytes inside a block of size 24 free'd
==25640==    at 0x483997B: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25640==    by 0x4863DAE: l_netlink_destroy (netlink.c:377)
==25640==    by 0x4849F0B: mptcpd_nm_destroy (network_monitor.c:972)
==25640==    by 0x10BD17: mptcpd_pm_destroy (path_manager.c:764)
==25640==    by 0x10A4AE: test_pm_destroy (test-path-manager.c:51)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==    by 0x485D4D7: l_queue_foreach (queue.c:441)
==25640==    by 0x4860B0C: l_main_iterate (main.c:486)
==25640==    by 0x4860B8B: l_main_run (main.c:520)
==25640==    by 0x10A5C6: main (test-path-manager.c:127)
==25640==  Block was alloc'd at
==25640==    at 0x483874F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25640==    by 0x485B76D: l_malloc (util.c:62)
==25640==    by 0x485D04D: l_queue_new (queue.c:63)
==25640==    by 0x4863D1D: l_netlink_new (netlink.c:359)
==25640==    by 0x484A008: mptcpd_nm_create (network_monitor.c:873)
==25640==    by 0x10BE04: mptcpd_pm_create (path_manager.c:748)
==25640==    by 0x10A3E0: test_pm_create (test-path-manager.c:38)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==    by 0x485D4D7: l_queue_foreach (queue.c:441)
==25640==    by 0x4860B0C: l_main_iterate (main.c:486)
==25640== 
==25640== Invalid write of size 8
==25640==    at 0x485D150: l_queue_push_tail (queue.c:147)
==25640==    by 0x4863F15: l_netlink_send (netlink.c:438)
==25640==    by 0x484939B: send_getaddr_command (network_monitor.c:845)
==25640==    by 0x4863792: destroy_command (netlink.c:76)
==25640==    by 0x485D9DB: l_hashmap_destroy (hashmap.c:336)
==25640==    by 0x4863DC9: l_netlink_destroy (netlink.c:379)
==25640==    by 0x4849F0B: mptcpd_nm_destroy (network_monitor.c:972)
==25640==    by 0x10BD17: mptcpd_pm_destroy (path_manager.c:764)
==25640==    by 0x10A4AE: test_pm_destroy (test-path-manager.c:51)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==  Address 0x4ac6940 is 0 bytes inside a block of size 24 free'd
==25640==    at 0x483997B: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25640==    by 0x4863DAE: l_netlink_destroy (netlink.c:377)
==25640==    by 0x4849F0B: mptcpd_nm_destroy (network_monitor.c:972)
==25640==    by 0x10BD17: mptcpd_pm_destroy (path_manager.c:764)
==25640==    by 0x10A4AE: test_pm_destroy (test-path-manager.c:51)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==    by 0x485D4D7: l_queue_foreach (queue.c:441)
==25640==    by 0x4860B0C: l_main_iterate (main.c:486)
==25640==    by 0x4860B8B: l_main_run (main.c:520)
==25640==    by 0x10A5C6: main (test-path-manager.c:127)
==25640==  Block was alloc'd at
==25640==    at 0x483874F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25640==    by 0x485B76D: l_malloc (util.c:62)
==25640==    by 0x485D04D: l_queue_new (queue.c:63)
==25640==    by 0x4863D1D: l_netlink_new (netlink.c:359)
==25640==    by 0x484A008: mptcpd_nm_create (network_monitor.c:873)
==25640==    by 0x10BE04: mptcpd_pm_create (path_manager.c:748)
==25640==    by 0x10A3E0: test_pm_create (test-path-manager.c:38)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==    by 0x485D4D7: l_queue_foreach (queue.c:441)
==25640==    by 0x4860B0C: l_main_iterate (main.c:486)
==25640== 
==25640== Invalid read of size 4
==25640==    at 0x485D158: l_queue_push_tail (queue.c:149)
==25640==    by 0x4863F15: l_netlink_send (netlink.c:438)
==25640==    by 0x484939B: send_getaddr_command (network_monitor.c:845)
==25640==    by 0x4863792: destroy_command (netlink.c:76)
==25640==    by 0x485D9DB: l_hashmap_destroy (hashmap.c:336)
==25640==    by 0x4863DC9: l_netlink_destroy (netlink.c:379)
==25640==    by 0x4849F0B: mptcpd_nm_destroy (network_monitor.c:972)
==25640==    by 0x10BD17: mptcpd_pm_destroy (path_manager.c:764)
==25640==    by 0x10A4AE: test_pm_destroy (test-path-manager.c:51)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==  Address 0x4ac6950 is 16 bytes inside a block of size 24 free'd
==25640==    at 0x483997B: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25640==    by 0x4863DAE: l_netlink_destroy (netlink.c:377)
==25640==    by 0x4849F0B: mptcpd_nm_destroy (network_monitor.c:972)
==25640==    by 0x10BD17: mptcpd_pm_destroy (path_manager.c:764)
==25640==    by 0x10A4AE: test_pm_destroy (test-path-manager.c:51)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==    by 0x485D4D7: l_queue_foreach (queue.c:441)
==25640==    by 0x4860B0C: l_main_iterate (main.c:486)
==25640==    by 0x4860B8B: l_main_run (main.c:520)
==25640==    by 0x10A5C6: main (test-path-manager.c:127)
==25640==  Block was alloc'd at
==25640==    at 0x483874F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25640==    by 0x485B76D: l_malloc (util.c:62)
==25640==    by 0x485D04D: l_queue_new (queue.c:63)
==25640==    by 0x4863D1D: l_netlink_new (netlink.c:359)
==25640==    by 0x484A008: mptcpd_nm_create (network_monitor.c:873)
==25640==    by 0x10BE04: mptcpd_pm_create (path_manager.c:748)
==25640==    by 0x10A3E0: test_pm_create (test-path-manager.c:38)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640==    by 0x10A4E7: idle_callback (test-path-manager.c:86)
==25640==    by 0x4860305: idle_dispatch (main.c:333)
==25640==    by 0x485D4D7: l_queue_foreach (queue.c:441)
==25640==    by 0x4860B0C: l_main_iterate (main.c:486)
==25640== 
==25640== 
==25640== HEAP SUMMARY:
==25640==     in use at exit: 16 bytes in 1 blocks
==25640==   total heap usage: 77 allocs, 76 frees, 76,319 bytes allocated
==25640== 
==25640== 16 bytes in 1 blocks are definitely lost in loss record 1 of 1
==25640==    at 0x483874F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==25640==    by 0x485B76D: l_malloc (util.c:62)
==25640==    by 0x485D11A: l_queue_push_tail (queue.c:136)
==25640==    by 0x4863F15: l_netlink_send (netlink.c:438)
==25640==    by 0x484939B: send_getaddr_command (network_monitor.c:845)
==25640==    by 0x4863792: destroy_command (netlink.c:76)
==25640==    by 0x485D9DB: l_hashmap_destroy (hashmap.c:336)
==25640==    by 0x4863DC9: l_netlink_destroy (netlink.c:379)
==25640==    by 0x4849F0B: mptcpd_nm_destroy (network_monitor.c:972)
==25640==    by 0x10BD17: mptcpd_pm_destroy (path_manager.c:764)
==25640==    by 0x10A4AE: test_pm_destroy (test-path-manager.c:51)
==25640==    by 0x485C238: l_test_run (test.c:83)
==25640== 
==25640== LEAK SUMMARY:
==25640==    definitely lost: 16 bytes in 1 blocks
==25640==    indirectly lost: 0 bytes in 0 blocks
==25640==      possibly lost: 0 bytes in 0 blocks
==25640==    still reachable: 0 bytes in 0 blocks
==25640==         suppressed: 0 bytes in 0 blocks
==25640== 
==25640== For counts of detected and suppressed errors, rerun with: -v
==25640== ERROR SUMMARY: 7 errors from 6 contexts (suppressed: 0 from 0)
```

**Desktop (please complete the following information):**
 - Linux Kernel: 5.0.0
 - Compiler: gcc 8.3

**Additional context**
The call stack shows the `static` function `send_getaddr_command()` being called as the Netlink destroy command.  That really shouldn't happen, but occurs because of a workaround in the mptcpd network monitor for an issue in the ELL `l_netlink` API that allows the second call to `l_netlink_send()` to be processed asynchronously prior to completion of the first `l_netlink_send()`.  The code in question is in lib/network_monitor.c:
```c
        /**
         * Get network interface information.
         *
         * @note We force the second rtnetlink command, RTM_GETADDR,
         *       to be sent after this one completes by doing so in
         *       the destroy callback for this command.  That
         *       guarantees that the potential multipart message
         *       response from this dump is fully read prior to
         *       sending the second command.  This works around an
         *       issue in ELL where it was possible that the second
         *       command would be sent prior to receiving all of the
         *       parts of the multipart @c RTM_GETLINK response, which
         *       resulted in an EBUSY error.
         */
        struct ifinfomsg link_msg = { .ifi_family = AF_UNSPEC };
        if (l_netlink_send(nm->rtnl,
                           RTM_GETLINK,
                           NLM_F_DUMP,
                           &link_msg,
                           sizeof(link_msg),
                           handle_rtm_getlink,
                           nm,
                           send_getaddr_command)
            == 0) {
                l_error("Unable to obtain network devices.");
                mptcpd_nm_destroy(nm);
                return NULL;
        }
```
The `send_getaddr_command()` function gets called as the "destroy command" even though that is not what we really want in the case of the `tests/test-path-manager` unit test.  The `test/test-network-monitor` unit test doesn't exhibit a memory leak, so we should look into what is done differently in `tests/test-path-manager` that ultimately triggers the leak.

### PR DESCRIPTION
**Pull request by ossama-othman**
Fix a memory leak that occurred when destroying a network monitor
instance that hasn't been fully initialized.  In particular, do not
attempt to retrieve network addresses if network interfaces are not
being tracked by the mptcpd network monitor.

The memory leak was caused by an incomplete attempt to retrieve
network addresses during mptcpd network monitor destruction.  Network
address retrieval is not necessary during mptcpd network monitor
destruction, but is unnecessarily triggered because of an ELL related
workaround that forces network address retrieval through the rtnetlink
API to occur only after network interface retrieval completes by
leveraging the netlink command "destroy" function as the trigger for
address retrieval.

Fixes #17.

### CODE REVIEW

File: lib/network_monitor.c [hunk 1]
```diff
@@ -893,6 +893,13 @@ static void send_getaddr_command(void *user_data)
 {
         struct mptcpd_nm *const nm = user_data;
 
+        /*
+          Don't bother attempting to retrieve IP addresses if no
+          network interfaces are being tracked.
+         */
+        if (l_queue_isempty(nm->interfaces))
```
Comment (mjmartineau) [inline lib/network_monitor.c]: It looks like this is depending on the `NULL` assignment in `mptcpd_nm_destroy()`, but if that was assigned then `nm` has already been freed prior to getting dereferenced here.

File: lib/network_monitor.c [hunk 2]
```diff
@@ -1021,6 +1028,7 @@ void mptcpd_nm_destroy(struct mptcpd_nm *nm)
                 l_error("Failed to unregister IPv6 monitor.");
 
         l_queue_destroy(nm->interfaces, mptcpd_interface_destroy);
+        nm->interfaces = NULL;
 
         l_netlink_destroy(nm->rtnl);
         l_free(nm);
```
Comment (mjmartineau) [inline lib/network_monitor.c]: Maybe defer `l_free(nm)` until the netlink call destructor runs if needed? If that netlink case is the only one, maybe some flag in the `nm` struct would be enough rather than full-blown refcounting.

File: lib/network_monitor.c (hunk 1 above)
Comment (ossama-othman) [reply lib/network_monitor.c]: I'm not sure I follow.  `nm` hasn't been freed yet at this point.  Only `nm->interfaces` has been freed.  This function gets called in two cases:

1. Immediately after network interface retrieval through `rtnetlink` completes.
2. During destruction of the `l_netlink` object used to retrieve the network interfaces and addresses.  In this case, the `l_netlink` object only get destroyed after thiis function returns.

In both cases, `nm` hasn't been freed yet.  `nm` is freed after the `l_netlink` object, i.e. `nm->rtnl` is destroyed.

File: lib/network_monitor.c (hunk 2 above)
Comment (ossama-othman) [reply lib/network_monitor.c]: Perhaps I'm missing something but I don't see why that would be necessary.  At this point in the code we should already know that nothing else is using `nm`.

The one exception I can think of is plugins that run asynchronous operations could be holding on to a reference to `nm` during network monitor destruction.  To address that case, I believe we'd have to defer network monitor destruction until after plugins are unloaded.

File: lib/network_monitor.c (hunk 1 above)
Comment (mjmartineau) [reply lib/network_monitor.c]: Ok, I was only thinking of it running asynchronously and didn't realize it would get invoked during `l_netlink_destroy()`

File: lib/network_monitor.c (hunk 2 above)
Comment (mjmartineau) [reply lib/network_monitor.c]: That case (async operations during destruction) is what I was referring to - I assumed that the two functions modified in the patch were coupled in order to address that scenario. That is, the `l_queue_isempty()` at line 900 wasn't doing the right thing unless `nm->interfaces` was nulled out at line 1031.

Comment (mjmartineau) [reply lib/network_monitor.c]: If this async case doesn't actually happen (or can't happen), then the commit looks fine.

File: lib/network_monitor.c (hunk 1 above)
Comment (ossama-othman) [reply lib/network_monitor.c]: Ideally this code shouldn't run during `l_netlink_destroy()` at all, but the workaround for sequential `l_netlink_send()` calls currently forces mptcpd to do so.  I'll try to come up with an alternative approach.

File: lib/network_monitor.c (hunk 2 above)
Comment (ossama-othman) [reply lib/network_monitor.c]: I'll adjust the network monitor life cycle so that it always exists for the life of all plugins to at least address the one async exception I could think of.  Hopefully there are no other async issues to be concerned about.

If I get some time I'll take a look at ELL's `l_netlink` command processing code to see if I can make it match the better `l_genl` behavior, and submit a patch upstream.

Comment (ossama-othman) [reply lib/network_monitor.c]: PR #55 contains the changes that extend path manager and network monitor lifetimes beyond plugin lifetimes.

**Comment by ossama-othman** [comment]
@mjmartineau I don't have any other changes for this pull request.  Any objections to merging it?

**Comment by mjmartineau** [comment]
Looks good to me
